server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mi?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-request-size: 20971520
      max-file-size: 20971520
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    database: 0


mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.mall.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  pattern:
    console: '%d{yyyy-MM-dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
    file: '%d{yyyy-MM-dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'

#  file:
#    path: 'd:\workspace\mi-mall\log'
#    name: mall.log


qiniu:
  key:
  sk:
  bucket:
